---
- name: Create "/tmp/sp_file_list.{{ date_time_stamp }}"
  shell: |
    jq -r '.packages | to_entries[] | .value.checksums | keys[]' {{ sp_manifest_dir }}/*.json | sort -u | sed 's/^/\//' > "/tmp/sp_file_list.{{ date_time_stamp }}" 
  changed_when: false

- name: Fetch "/tmp/sp_file_list.{{ date_time_stamp }}" to "/tmp/sp_file_list_from_node/{{ ansible_host }}/sp_file_list" on localhost
  fetch:
    src: "/tmp/sp_file_list.{{ date_time_stamp }}"
    dest: "/tmp/sp_file_list_from_node/{{ ansible_host }}/sp_file_list"
    flat: yes
  changed_when: false

- name: Create "/tmp/sp_file_list_from_node/*/sp_file_list_diff"
  shell: |
    for f in /tmp/sp_file_list_from_node/*/sp_file_list
    do
      diff /tmp/sp_file_list_from_vault/sp_file_list ${f} | grep -e '^< ' | sed 's/^< //' > ${f}_diff 
    done
  delegate_to: localhost
  run_once: true
  changed_when: false
