---
- name: Create "/tmp/sp_file_list.{{ date_time_stamp }}"
  shell: |
    jq -r '.packages | to_entries[] | .value.checksums | keys[]' {{ sp_manifest_dir }}/*.json | sort -u | sed 's/^/\//' > "/tmp/sp_file_list.{{ date_time_stamp }}" 
  changed_when: false

- name: Fetch "/tmp/sp_file_list.{{ date_time_stamp }}" to "/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_file_list" on localhost
  fetch:
    src: "/tmp/sp_file_list.{{ date_time_stamp }}"
    dest: "/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_file_list"
    flat: yes
  changed_when: false

- name: Check whether files enlisted in "/tmp/sp_file_list.{{ date_time_stamp }}" exist on node
  shell: |
    while IFS= read -r p
    do
      if ! [ -f $p ]; then echo $p >> "/tmp/sp_files_list.not_found.{{ date_time_stamp }}"; fi
    done < "/tmp/sp_file_list.{{ date_time_stamp }}"
  changed_when: false

- name: Check whether file "/tmp/sp_files_list.not_found.{{ date_time_stamp }}" created on node
  shell: |
    if [ -f /tmp/sp_files_list.not_found.{{ date_time_stamp }} ]; then exit 1; fi
  register: check_not_found
  ignore_errors: true
  changed_when: false

- name: Fetch "/tmp/sp_file_list.not_found.{{ date_time_stamp }}" to "/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_file_list.not_found on localhost
  fetch:
    src: "/tmp/sp_file_list.not_found.{{ date_time_stamp }}"
    dest: "/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_file_list.not_found"
    flat: yes
  changed_when: false
  when:
    - check_not_found is defined
    - check_not_found.rc is defined
    - check_not_found.rc == 1
