#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  roles: []
  tasks: []

- name: Example 1
  hosts: storpool
  gather_subset: 'min'
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - { role: '../shared/roles/try-become-methods' }
  tasks:
    - name: Print ansible_distribution
      debug:
        var: ansible_distribution

    - name: Print ansible_distribution_major_version
      debug:
        var: ansible_distribution_major_version
  
    - name: Print ansible_pkg_mgr
      debug:
        var: ansible_pkg_mgr
