---
- name: Copy sp_file_list_from_vault to node
  copy:
    src: /tmp/sp_file_list_from_vault/sp_file_list
    dest: /tmp/sp_file_list_from_vault
    mode: preserve

- name: Copy sp_remove_files to node
  copy:
    src: /tmp/sp_file_list_from_vault/sp_remove_files
    dest: /tmp/sp_remove_files
    mode: preserve

- name: Remove "/tmp/sp_file_list_diff" if exists
  file:
    path: /tmp/sp_file_list_diff
    state: absent
  changed_when: false

- name: Remove "/tmp/sp_file_list_diff_found" if exists
  file:
    path: /tmp/sp_file_list_diff_found
    state: absent
  changed_when: false

- name: Remove "/tmp/sp_remove_files_found" if exists
  file:
    path: /tmp/sp_remove_files_found
    state: absent
  changed_when: false

- name: Try to find stale or obsolete storpool files on node
  shell: |
    comm -23 /tmp/sp_file_list_from_vault /tmp/sp_file_list > /tmp/sp_file_list_diff
    while IFS= read -r p
    do
      if [ -f $p ]; then echo $p >> /tmp/sp_file_list_diff_found; fi
    done < /tmp/sp_file_list_diff
    while IFS= read -r p
    do
      if [ -f $p ]; then echo $p >> /tmp/sp_remove_files_found; fi
    done < /tmp/sp_remove_files
  changed_when: false

- name: Check whether file "/tmp/sp_file_list_diff_found" created on node
  shell: |
    if [ -f /tmp/sp_file_list_diff_found ]; then exit 1; fi
  register: sp_file_list_diff_found
  ignore_errors: true
  changed_when: false

- name: Fetch "/tmp/sp_file_list_diff_found" to "/tmp/sp_file_list_from_node/<inventory_hostname>/sp_file_list_diff_found" on localhost
  fetch:
    src: /tmp/sp_file_list_diff_found
    dest: "/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_file_list_diff_found"
    flat: yes
  changed_when: false
  when:
    - sp_file_list_diff_found is defined
    - sp_file_list_diff_found.rc is defined
    - sp_file_list_diff_found.rc == 1

- name: Check whether file "/tmp/sp_remove_files_found" created on node
  shell: |
    if [ -f /tmp/sp_remove_files_found ]; then exit 1; fi
  register: sp_remove_files_found
  ignore_errors: true
  changed_when: false

- name: Fetch "/tmp/sp_remove_files_found" to "/tmp/sp_file_list_from_node/<inventory_hostname>/sp_remove_files_found" on localhost
  fetch:
    src: /tmp/sp_remove_files_found
    dest: "/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_remove_files_found"
    flat: yes
  changed_when: false
  when:
    - sp_remove_files_found is defined
    - sp_remove_files_found.rc is defined
    - sp_remove_files_found.rc == 1