---
- name: Create "/tmp/sp_file_list_from_node/*/sp_file_list_diff"
  shell: |
    for f in /tmp/sp_file_list_from_node/*/sp_file_list
    do
      comm -23 /tmp/sp_file_list_from_vault/sp_file_list ${f} > ${f}_diff 
    done
  delegate_to: localhost
  run_once: true
  changed_when: false

- name: Remove "/tmp/sp_file_list_diff_found" if exists
  file:
    path: /tmp/sp_file_list_diff_found
    state: absent
  changed_when: false

- name: Remove "/tmp/sp_remove_files_found" if exists
  file:
    path: /tmp/sp_remove_files_found
    state: absent
  changed_when: false

- name: Try to find redundant storpool files on node (from sp_file_list_diff)
  shell: |
    if [ -f {{ item }} ]; then echo {{ item }} >> /tmp/sp_file_list_diff_found; fi
  changed_when: false
  loop: "{{ lookup('file', '/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_file_list_diff').splitlines() }}"

- name: Check whether file "/tmp/sp_file_list_diff_found" created on node
  shell: |
    if [ -f /tmp/sp_file_list_diff_found ]; then exit 1; fi
  register: sp_file_list_diff_found
  ignore_errors: true
  changed_when: false

- name: Print sp_file_list_diff_found.rc
  debug:
    var: sp_file_list_diff_found.rc
  when:
    - sp_file_list_diff_found is defined
    - sp_file_list_diff_found.rc is defined

- name: Try to find obsolete storpool files on node (from sp_remove_files)
  shell: |
    if [ -f {{ item }} ]; then echo {{ item }} >> /tmp/sp_remove_files_found; fi
  changed_when: false
  loop: "{{ lookup('file', '/tmp/sp_file_list_from_vault/sp_remove_files').splitlines() }}"

- name: Check whether file "/tmp/sp_remove_files_found" created on node
  shell: |
    if [ -f /tmp/sp_remove_files_found ]; then exit 1; fi
  register: sp_remove_files_found
  ignore_errors: true
  changed_when: false

- name: Print sp_remove_files_found.rc
  debug:
    var: sp_remove_files_found.rc
  when:
    - sp_remove_files_found is defined
    - sp_remove_files_found.rc is defined