---
- name: Copy sp_file_list_from_vault to node (RedHat family)
  copy:
    src: "{{ sp_file_list_from_vault_dir }}/sp_file_list_redhat"
    dest: /tmp/sp_file_list_from_vault
    mode: preserve
  when:
    - ansible_os_family == "RedHat" or
      ansible_os_family == "AlmaLinux" or
      ansible_os_family == "Rocky"

- name: Copy sp_file_list_from_vault to node (Debian family)
  copy:
    src: "{{ sp_file_list_from_vault_dir }}/sp_file_list_debian"
    dest: /tmp/sp_file_list_from_vault
    mode: preserve
  when:
    - ansible_os_family == "Debian"

- name: Copy sp_remove_files to node (RedHat family)
  copy:
    src: "{{ sp_file_list_from_vault_dir }}/sp_remove_files_redhat"
    dest: /tmp/sp_remove_files
    mode: preserve
  when:
    - ansible_os_family == "RedHat" or
      ansible_os_family == "AlmaLinux" or
      ansible_os_family == "Rocky"

- name: Copy sp_remove_files to node (Debian family)
  copy:
    src: "{{ sp_file_list_from_vault_dir }}/sp_remove_files_debian"
    dest: /tmp/sp_remove_files
    mode: preserve
  when:
    - ansible_os_family == "Debian"

- name: Remove temp files if exist
  file:
    path: "{{ item }}"
    state: absent
  changed_when: false
  loop:
    - '/tmp/sp_file_list_diff'
    - '/tmp/sp_stale_files_found'
    - '/tmp/sp_remove_files_found'

- name: Try to find stale storpool files on node
  shell: |
    comm -23 /tmp/sp_file_list_from_vault /tmp/sp_file_list > /tmp/sp_file_list_diff
    while IFS= read -r p
    do
      if [ -f $p ]; then echo $p >> /tmp/sp_stale_files_found; fi
    done < /tmp/sp_file_list_diff
    while IFS= read -r p
    do
      if [ -f $p ]; then echo $p >> /tmp/sp_remove_files_found; fi
    done < /tmp/sp_remove_files
  changed_when: false

- name: Check whether file "/tmp/sp_stale_files_found" created on node
  shell: |
    if [ -f /tmp/sp_stale_files_found ]; then exit 1; fi
  register: sp_stale_files_found
  ignore_errors: true
  changed_when: false

- name: Fetch "/tmp/sp_stale_files_found" to localhost
  fetch:
    src: /tmp/sp_stale_files_found
    dest: "{{ sp_file_list_from_node_dir }}/{{ inventory_hostname }}/sp_stale_files_found"
    flat: yes
  when:
    - sp_stale_files_found is defined
    - sp_stale_files_found.rc is defined
    - sp_stale_files_found.rc == 1

- name: Print path to sp_stale_files_found
  debug:
    msg:
    - "{{ sp_file_list_from_node_dir }}/{{ inventory_hostname }}/sp_stale_files_found"
  when:
    - sp_stale_files_found is defined
    - sp_stale_files_found.rc is defined
    - sp_stale_files_found.rc == 1

- name: Check whether file "/tmp/sp_remove_files_found" created on node
  shell: |
    if [ -f /tmp/sp_remove_files_found ]; then exit 1; fi
  register: sp_remove_files_found
  ignore_errors: true
  changed_when: false

- name: Fetch "/tmp/sp_remove_files_found" to localhost
  fetch:
    src: /tmp/sp_remove_files_found
    dest: "{{ sp_file_list_from_node_dir }}/{{ inventory_hostname }}/sp_remove_files_found"
    flat: yes
  when:
    - sp_remove_files_found is defined
    - sp_remove_files_found.rc is defined
    - sp_remove_files_found.rc == 1

- name: Print path to sp_remove_files_found
  debug:
    msg:
    - "{{ sp_file_list_from_node_dir }}/{{ inventory_hostname }}/sp_remove_files_found"
  when:
    - sp_remove_files_found is defined
    - sp_remove_files_found.rc is defined
    - sp_remove_files_found.rc == 1
