---
- name: Try sudo method
  command: /bin/true
  become: true
  become_method: sudo
  register: try_sudo_result
  changed_when: false
  ignore_errors: true
  when:
    - sp_become_method is not defined
    - ansible_effective_user_id != 0

- name: Setting sp_become_method fact (sudo)
  set_fact:
    sp_become_method: 'sudo'
    cacheable: yes
  when:
    - sp_become_method is not defined
    - try_sudo_result is defined
    - try_sudo_result.rc is defined and try_sudo_result.rc == 0
    
- name: Try su method
  command: /bin/true
  become: true
  become_method: su
  register: try_su_result
  changed_when: false
  ignore_errors: true
  when:
    - sp_become_method is not defined
    - ansible_effective_user_id != 0

- name: Setting sp_become_method fact (su)
  set_fact:
    sp_become_method: 'su'
    cacheable: yes
  when:
    - sp_become_method is not defined
    - try_su_result is defined
    - try_su_result.rc is defined and try_su_result.rc == 0
