#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  tasks: []

- name: Gather storpool file lists from storpool vault
  hosts: vault
  gather_subset: 'min'
  vars_files:
    - vars/main.yml 
  roles:
    - role: 'roles/sp-file-list-from-vault'
      tags:
        - sp-file-list-from-vault
  tasks: []

- name: Gather storpool file lists from storpool nodes
  hosts: storpool
  gather_subset: 'min'
  ignore_errors: true
  ignore_unreachable: true
  vars_files:
    - vars/main.yml
  roles:
    - role: 'roles/sp-file-list-from-node'
      tags:
        - sp-file-list-from-node
  tasks: []
