#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  roles: []
  tasks: []

- name: Update of support key on hosts
  hosts: storpool
  gather_subset: 'min'
  vars:
    support_pub_key_path: files/support-key.pub
  tasks:
    - name: Extract support_key_with_comment
      shell: |
        grep "StorPool Support 2020 SSH key$" "{{ support_pub_key_path }}"
      register: support_key_with_comment
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Asserts for extract of support_key_with_comment
      assert:
        that:
          - support_key_with_comment.stdout_lines | length == 1
        fail_msg: "More than one key found in key source file"
      delegate_to: localhost
      run_once: true
      when:
        - support_key_with_comment is defined
        - support_key_with_comment.stdout_lines is defined

    - name: Extract support_key (algo & key only)
      shell: |
        echo "{{ support_key_with_comment.stdout }}" | cut -d ' ' -f 1,2
      register: support_key
      changed_when: false
      delegate_to: localhost
      run_once: true
      when:
        - support_key_with_comment is defined
        - support_key_with_comment.rc is defined and
          support_key_with_comment.rc == 0
        - support_key_with_comment.stdout is defined

    - name: Validation of support_key by search in key source file
      shell: |
        if [[ "$(grep "^{{ support_key.stdout }}" "{{ support_pub_key_path }}")" != "{{ support_key_with_comment.stdout }}" ]]; then exit 1; fi
      changed_when: false
      delegate_to: localhost
      run_once: true
      when:
        - support_key is defined
        - support_key.rc is defined and
          support_key.rc == 0
        - support_key.stdout is defined
        - support_key_with_comment.stdout is defined

    - name: Attempt to find support_key on hosts
      shell: |
        grep "^{{ support_key.stdout }}" "{{ ansible_env.HOME }}/.ssh/authorized_keys"
      register: support_key_found
      ignore_errors: yes
      changed_when: false
      when:
        - support_key is defined
        - support_key.rc is defined and
          support_key.rc == 0
        - support_key.stdout is defined

    - name: Asserts for attempt to find support_key on hosts
      assert:
        that:
          - support_key_found.rc <= 1
        fail_msg: "Attempt to find support_key on host failed: existance or absence of support_key is not confirmed."
      when:
        - support_key_found is defined
        - support_key_found.rc is defined

    - name: Setup new support_key on hosts
      shell: |
        echo "{{ support_key_with_comment.stdout }}" >> "{{ ansible_env.HOME }}/.ssh/authorized_keys"
      when:
        - support_key_found is defined
        - support_key_found.rc is defined and
          support_key_found.rc == 1
        - support_key_with_comment.stdout is defined

    - name: Validation of new support_key setup on hosts
      shell: |
        grep "^{{ support_key_with_comment.stdout }}$" "{{ ansible_env.HOME }}/.ssh/authorized_keys"
      register: support_key_validation
      changed_when: false
      when:
        - support_key_found is defined
        - support_key_found.rc is defined and
          support_key_found.rc == 1
        - support_key_with_comment.stdout is defined
