#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  roles: []
  tasks: []

- name: Ensure new support_key is set
  hosts: storpool
  gather_subset: 'min'
  tasks:
    - name: Ensure new support_key is set
      ansible.posix.authorized_key:
        user: "{{ ansible_env.USER }}"
        state: present
        key: "{{ lookup('file', 'files/support-key.pub') }}"
        exclusive: false
        manage_dir: false
