#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  roles: []
  tasks: []

- name: Update of support key on hosts
  hosts: storpool
  gather_facts: false
  become: true
  vars:
    support_pub_key_path: /home/tools/support-key.pub
  tasks:
    - name: Get support_key_with_comment
      shell: |
        grep "StorPool Support 2020 SSH key$" "{{ support_pub_key_path }}"
      register: support_key_with_comment
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Print support_key_with_comment
      debug:
        var: support_key_with_comment.stdout
      delegate_to: localhost
      run_once: true
      when:
        - support_key_with_comment is defined
        - support_key_with_comment.rc is defined and
          support_key_with_comment.rc == 0
        - support_key_with_comment.stdout is defined

    - name: Get support_key
      shell: |
        echo "{{ support_key_with_comment.stdout }}" | cut -d ' ' -f 1,2
      register: support_key
      changed_when: false
      delegate_to: localhost
      run_once: true
      when:
        - support_key_with_comment is defined
        - support_key_with_comment.rc is defined and
          support_key_with_comment.rc == 0
        - support_key_with_comment.stdout is defined

    - name: Print support_key
      debug:
        var: support_key.stdout
      delegate_to: localhost
      run_once: true
      when:
        - support_key is defined
        - support_key.rc is defined and
          support_key.rc == 0
        - support_key.stdout is defined

    - name: Validate support_key
      shell: |
        grep "^{{ support_key.stdout }}" "{{ support_pub_key_path }}"
      register: support_key_validation
      changed_when: false
      delegate_to: localhost
      run_once: true
      when:
        - support_key is defined
        - support_key.rc is defined and
          support_key.rc == 0
        - support_key.stdout is defined

    - name: Print support_key validation result
      debug:
        var: support_key_validation.stdout
      delegate_to: localhost
      run_once: true
      when:
        - support_key_validation is defined
        - support_key_validation.rc is defined and
          support_key_validation.rc == 0
        - support_key_validation.stdout is defined
