#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  tasks: []

- name: Remove stale files
  hosts: storpool
  gather_subset: 'min'
  ignore_unreachable: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Check whether file "{{ sp_stale_files_inv_dir }}/<inventory_hostname>/sp_stale_files_found" exists
      shell: |
        if [ -f {{ sp_stale_files_inv_dir }}/{{ inventory_hostname }}/sp_stale_files_found ]; then exit 1; fi
      register: sp_stale_files_found
      ignore_errors: true
      delegate_to: localhost
      changed_when: false

    - name: Show stale files per node
      debug:
        var: item
      delegate_to: localhost
      loop: >
        {{ lookup('file', '{{ sp_stale_files_inv_dir }}/{{ inventory_hostname }}/sp_stale_files_found').splitlines()
        if sp_stale_files_found is defined and
        sp_stale_files_found.rc is defined and
        sp_stale_files_found.rc == 1 else [] }}
      when:
        - sp_stale_files_found is defined
        - sp_stale_files_found.rc is defined
        - sp_stale_files_found.rc == 1

    - name: Confirm removal of stale files by the list above
      pause:
        prompt: "\nPlease, confirm the list of stale files above\n\nPress Enter to Confirm\nor Ctrl-C,A to Refuse and Abort"
      delegate_to: localhost

    - name: Simulate removal of stale files on node
      file:
        path: "{{ item }}"
        state: file
      ignore_errors: true
      become: "{{ ansible_effective_user_id != 0 }}"
      loop: >
        {{ lookup('file', '{{ sp_stale_files_inv_dir }}/{{ inventory_hostname }}/sp_stale_files_found').splitlines()
        if sp_stale_files_found is defined and
        sp_stale_files_found.rc is defined and
        sp_stale_files_found.rc == 1 else [] }}  
      when:
        - sp_stale_files_found is defined
        - sp_stale_files_found.rc is defined
        - sp_stale_files_found.rc == 1
