#!/usr/bin/env ansible-playbook
---
- name: Gather localhost's facts
  hosts: localhost
  gather_subset: 'min'
  tasks: []

- name: Show found stale files
  hosts: storpool
  gather_facts: false
  ignore_unreachable: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Check whether file "{{ sp_stale_files_inv_dir }}/<inventory_hostname>/sp_stale_files_found" exists
      stat:
        path: "{{ sp_stale_files_inv_dir }}/{{ inventory_hostname }}/sp_stale_files_found"
      register: sp_stale_files_found
      delegate_to: localhost

    - name: Show stale files per node
      debug:
        var: item
      delegate_to: localhost
      loop: >
        {{ lookup('file', '{{ sp_stale_files_inv_dir }}/{{ inventory_hostname }}/sp_stale_files_found').splitlines()
        if sp_stale_files_found.stat.exists else [] }}
      when:
        - sp_stale_files_found.stat.exists
