---
- name: Create "/tmp/sp_file_list_from_node/*/sp_file_list_diff"
  shell: |
    for f in /tmp/sp_file_list_from_node/*/sp_file_list
    do
      diff /tmp/sp_file_list_from_vault/sp_file_list ${f} | grep -e '^< ' | sed 's/^< //' > ${f}_diff 
    done
  delegate_to: localhost
  run_once: true
  changed_when: false

- name: Try to find redundant storpool files on node (from sp_file_list_diff)
  shell: |
    if [ -f {{ item }} ]; then echo {{ item }}; fi
  register: found_files
  changed_when: false
  loop: "{{ lookup('file', '/tmp/sp_file_list_from_node/{{ inventory_hostname }}/sp_file_list_diff').splitlines() }}"

- name: Print found files if any (from sp_file_list_diff)
  debug:
    var: found_files.stdout
  when:
    - found_files is defined
    - found_files.stdout is defined

- name: Try to find obsolete storpool files on node (from sp_remove_files)
  shell: |
    if [ -f {{ item }} ]; then echo {{ item }}; fi
  register: found_files
  changed_when: false
  loop: "{{ lookup('file', '/tmp/sp_file_list_from_vault/sp_remove_files').splitlines() }}"

- name: Print found files if any (from sp_remove_files)
  debug:
    var: found_files.stdout
  when:
    - found_files is defined
    - found_files.stdout is defined